name: buybetter
description: Comparador inteligente com georreferenciamento colaborativo.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.7
  geolocator: ^12.0.0
  google_maps_flutter: ^2.9.0
  geocoding: ^2.1.1
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
